// Datos reales de catálogos centralizados
// Fuente: src/shared/data/projectCatalogStorage.ts y mockDatabase.ts
// NO contiene datos ficticios, solo datos existentes validados en el sistema

import type { CatalogValue } from "./catalog.types";

export const CATALOG_VALUES_SEED: CatalogValue[] = [
  // ============ WRAPPING_TYPE (Envolturas - 3 items) ============
  {
    id: "wrap_001",
    catalogId: "catalog_wrapping_type",
    catalogCode: "wrapping_type",
    item: "ENV-001",
    name: "POUCH",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "wrap_002",
    catalogId: "catalog_wrapping_type",
    catalogCode: "wrapping_type",
    item: "ENV-002",
    name: "BOLSA",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "wrap_003",
    catalogId: "catalog_wrapping_type",
    catalogCode: "wrapping_type",
    item: "ENV-003",
    name: "LÁMINA",
    status: "Activo",
    sortOrder: 3,
  },

  // ============ SUBCLASSIFICATION (Sub-clasificación - 5 items) ============
  {
    id: "subclass_001",
    catalogId: "catalog_subclassification",
    catalogCode: "subclassification",
    item: "SUBCLASS-001",
    name: "SFDC - R&D",
    description: "Solicitud de desarrollo cliente - R&D",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "subclass_002",
    catalogId: "catalog_subclassification",
    catalogCode: "subclassification",
    item: "SUBCLASS-002",
    name: "SFDC - Técnica",
    description: "Solicitud de desarrollo cliente - Técnica",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "subclass_003",
    catalogId: "catalog_subclassification",
    catalogCode: "subclassification",
    item: "SUBCLASS-003",
    name: "Estructura",
    description: "Cambio en estructura",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "subclass_004",
    catalogId: "catalog_subclassification",
    catalogCode: "subclassification",
    item: "SUBCLASS-004",
    name: "Extensiones en línea",
    description: "Extensiones de línea existente",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "subclass_005",
    catalogId: "catalog_subclassification",
    catalogCode: "subclassification",
    item: "SUBCLASS-005",
    name: "No aplica",
    description: "No aplica sub-clasificación",
    status: "Activo",
    sortOrder: 5,
  },

  // ============ UNIT_MEASURE (Unidad de Medida - 7 items) ============
  {
    id: "um_001",
    catalogId: "catalog_unit_measure",
    catalogCode: "unit_measure",
    item: "UM-001",
    name: "unidad",
    description: "Unidad",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "um_002",
    catalogId: "catalog_unit_measure",
    catalogCode: "unit_measure",
    item: "UM-002",
    name: "millares",
    description: "Millares (miles de unidades)",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "um_003",
    catalogId: "catalog_unit_measure",
    catalogCode: "unit_measure",
    item: "UM-003",
    name: "kilos",
    description: "Kilogramos",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "um_004",
    catalogId: "catalog_unit_measure",
    catalogCode: "unit_measure",
    item: "UM-004",
    name: "metros",
    description: "Metros lineales",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "um_005",
    catalogId: "catalog_unit_measure",
    catalogCode: "unit_measure",
    item: "UM-005",
    name: "millones_unidades",
    description: "Millones de unidades",
    status: "Activo",
    sortOrder: 5,
  },
  {
    id: "um_006",
    catalogId: "catalog_unit_measure",
    catalogCode: "unit_measure",
    item: "UM-006",
    name: "toneladas",
    description: "Toneladas",
    status: "Activo",
    sortOrder: 6,
  },
  {
    id: "um_007",
    catalogId: "catalog_unit_measure",
    catalogCode: "unit_measure",
    item: "UM-007",
    name: "rollos",
    description: "Rollos",
    status: "Activo",
    sortOrder: 7,
  },

  // ============ SALE_TYPE (Tipo de Venta - 2 items) ============
  {
    id: "st_001",
    catalogId: "catalog_sale_type",
    catalogCode: "sale_type",
    item: "ST-001",
    name: "Nacional",
    description: "Venta dentro del país",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "st_002",
    catalogId: "catalog_sale_type",
    catalogCode: "sale_type",
    item: "ST-002",
    name: "Internacional",
    description: "Exportación",
    status: "Activo",
    sortOrder: 2,
  },

  // ============ INCOTERM (Incoterms - 11 items) ============
  {
    id: "ic_001",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-001",
    name: "EXW",
    description: "Ex Works - En fábrica",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "ic_002",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-002",
    name: "FCA",
    description: "Free Carrier - Libre transportista",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "ic_003",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-003",
    name: "CPT",
    description: "Carriage Paid To - Transporte pagado hasta",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "ic_004",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-004",
    name: "CIP",
    description: "Carriage and Insurance Paid - Transporte y seguro pagado",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "ic_005",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-005",
    name: "DAP",
    description: "Delivered at Place - Entregado en lugar",
    status: "Activo",
    sortOrder: 5,
  },
  {
    id: "ic_006",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-006",
    name: "DPU",
    description: "Delivered at Place Unloaded - Entregado descargado",
    status: "Activo",
    sortOrder: 6,
  },
  {
    id: "ic_007",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-007",
    name: "DDP",
    description: "Delivered Duty Paid - Entregado derechos pagados",
    status: "Activo",
    sortOrder: 7,
  },
  {
    id: "ic_008",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-008",
    name: "FAS",
    description: "Free Alongside Ship - Libre al costado del buque",
    status: "Activo",
    sortOrder: 8,
  },
  {
    id: "ic_009",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-009",
    name: "FOB",
    description: "Free On Board - Libre a bordo",
    status: "Activo",
    sortOrder: 9,
  },
  {
    id: "ic_010",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-010",
    name: "CFR",
    description: "Cost and Freight - Costo y flete",
    status: "Activo",
    sortOrder: 10,
  },
  {
    id: "ic_011",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-011",
    name: "CIF",
    description: "Cost, Insurance and Freight - Costo, seguro y flete",
    status: "Activo",
    sortOrder: 11,
  },

  // ============ DESTINATION_COUNTRY (Países de Destino - 20 items) ============
  {
    id: "dc_001",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "PE",
    name: "Perú",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "dc_002",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "CL",
    name: "Chile",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "dc_003",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "CO",
    name: "Colombia",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "dc_004",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "EC",
    name: "Ecuador",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "dc_005",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "AR",
    name: "Argentina",
    status: "Activo",
    sortOrder: 5,
  },
  {
    id: "dc_006",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "BR",
    name: "Brasil",
    status: "Activo",
    sortOrder: 6,
  },
  {
    id: "dc_007",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "BO",
    name: "Bolivia",
    status: "Activo",
    sortOrder: 7,
  },
  {
    id: "dc_008",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "UY",
    name: "Uruguay",
    status: "Activo",
    sortOrder: 8,
  },
  {
    id: "dc_009",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "PY",
    name: "Paraguay",
    status: "Activo",
    sortOrder: 9,
  },
  {
    id: "dc_010",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "VE",
    name: "Venezuela",
    status: "Activo",
    sortOrder: 10,
  },
  {
    id: "dc_011",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "MX",
    name: "México",
    status: "Activo",
    sortOrder: 11,
  },
  {
    id: "dc_012",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "US",
    name: "Estados Unidos",
    status: "Activo",
    sortOrder: 12,
  },
  {
    id: "dc_013",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "CA",
    name: "Canadá",
    status: "Activo",
    sortOrder: 13,
  },
  {
    id: "dc_014",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "PA",
    name: "Panamá",
    status: "Activo",
    sortOrder: 14,
  },
  {
    id: "dc_015",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "CR",
    name: "Costa Rica",
    status: "Activo",
    sortOrder: 15,
  },
  {
    id: "dc_016",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "GT",
    name: "Guatemala",
    status: "Activo",
    sortOrder: 16,
  },
  {
    id: "dc_017",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "SV",
    name: "El Salvador",
    status: "Activo",
    sortOrder: 17,
  },
  {
    id: "dc_018",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "HN",
    name: "Honduras",
    status: "Activo",
    sortOrder: 18,
  },
  {
    id: "dc_019",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "NI",
    name: "Nicaragua",
    status: "Activo",
    sortOrder: 19,
  },
  {
    id: "dc_020",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "DO",
    name: "República Dominicana",
    status: "Activo",
    sortOrder: 20,
  },

  // ============ CURRENCY (Moneda - 3 items) ============
  {
    id: "cur_001",
    catalogId: "catalog_currency",
    catalogCode: "currency",
    item: "PEN",
    name: "Soles",
    description: "Sol peruano",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "cur_002",
    catalogId: "catalog_currency",
    catalogCode: "currency",
    item: "USD",
    name: "Dólares",
    description: "Dólar estadounidense",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "cur_003",
    catalogId: "catalog_currency",
    catalogCode: "currency",
    item: "EUR",
    name: "Euros",
    description: "Euro",
    status: "Activo",
    sortOrder: 3,
  },

  // ============ PRINT_CLASS (Clase de Impresión - 3 items) ============
  // Valores oficiales según Excel funcional
  {
    id: "pc_001",
    catalogId: "catalog_print_class",
    catalogCode: "print_class",
    item: "PC-001",
    name: "Flexo",
    description: "Impresión flexográfica",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "pc_002",
    catalogId: "catalog_print_class",
    catalogCode: "print_class",
    item: "PC-002",
    name: "Huecograbado",
    description: "Impresión en huecograbado",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "pc_003",
    catalogId: "catalog_print_class",
    catalogCode: "print_class",
    item: "PC-003",
    name: "Sin impresión",
    description: "Película sin impresión",
    status: "Activo",
    sortOrder: 3,
  },

  // ============ PRINT_TYPE (Tipo de Impresión - 2 items) ============
  // Valores oficiales según Excel funcional
  {
    id: "pt_001",
    catalogId: "catalog_print_type",
    catalogCode: "print_type",
    item: "PT-001",
    name: "Repetitivo",
    description: "Impresión repetitiva",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "pt_002",
    catalogId: "catalog_print_type",
    catalogCode: "print_type",
    item: "PT-002",
    name: "Continuo",
    description: "Impresión continua",
    status: "Activo",
    sortOrder: 2,
  },

  // ============ STRUCTURE_TYPE (Tipo de Estructura - 4 items) ============
  {
    id: "st_str_001",
    catalogId: "catalog_structure_type",
    catalogCode: "structure_type",
    item: "ST-001",
    name: "Monocapa",
    description: "Estructura de una capa",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "st_str_002",
    catalogId: "catalog_structure_type",
    catalogCode: "structure_type",
    item: "ST-002",
    name: "Bilaminado",
    description: "Estructura de dos capas",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "st_str_003",
    catalogId: "catalog_structure_type",
    catalogCode: "structure_type",
    item: "ST-003",
    name: "Trilaminado",
    description: "Estructura de tres capas",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "st_str_004",
    catalogId: "catalog_structure_type",
    catalogCode: "structure_type",
    item: "ST-004",
    name: "Tetralaminado",
    description: "Estructura de cuatro capas",
    status: "Activo",
    sortOrder: 4,
  },

  // ============ FINAL_USE (Uso Final - 10+ items de FINAL_USE_CATALOG) ============
  {
    id: "fu_001",
    catalogId: "catalog_final_use",
    catalogCode: "final_use",
    item: "UF-001",
    name: "Adhesive Bandages/Plasters",
    description: "Categoría Healthcare",
    status: "Activo",
    sortOrder: 1,
  },

  // ============ PLANT (Plantas - 4 items) ============
  {
    id: "plant_001",
    catalogId: "catalog_plant",
    catalogCode: "plant",
    item: "AF-LIM",
    name: "AF Lima",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "plant_002",
    catalogId: "catalog_plant",
    catalogCode: "plant",
    item: "AF-SL",
    name: "AF San Luis",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "plant_003",
    catalogId: "catalog_plant",
    catalogCode: "plant",
    item: "AF-CAL",
    name: "AF Cali",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "plant_004",
    catalogId: "catalog_plant",
    catalogCode: "plant",
    item: "AF-STN",
    name: "AF Santiago Norte",
    status: "Activo",
    sortOrder: 4,
  },

  // ============ CLIENT_TYPE (Tipo de Cliente - 4 items) ============
  {
    id: "ct_001",
    catalogId: "catalog_client_type",
    catalogCode: "client_type",
    item: "CT-001",
    name: "Distribuidor",
    description: "Cliente distribuidor",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "ct_002",
    catalogId: "catalog_client_type",
    catalogCode: "client_type",
    item: "CT-002",
    name: "Fabricante",
    description: "Cliente fabricante",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "ct_003",
    catalogId: "catalog_client_type",
    catalogCode: "client_type",
    item: "CT-003",
    name: "Retailer",
    description: "Cliente retail/comercio",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "ct_004",
    catalogId: "catalog_client_type",
    catalogCode: "client_type",
    item: "CT-004",
    name: "Consumidor Final",
    description: "Consumidor directo",
    status: "Activo",
    sortOrder: 4,
  },

  // ============ CLIENT_SECTOR (Sector Cliente - 6 items) ============
  {
    id: "cs_001",
    catalogId: "catalog_client_sector",
    catalogCode: "client_sector",
    item: "CS-001",
    name: "Alimentos y Bebidas",
    description: "Industria de alimentos y bebidas",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "cs_002",
    catalogId: "catalog_client_sector",
    catalogCode: "client_sector",
    item: "CS-002",
    name: "Farmacéutico",
    description: "Industria farmacéutica",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "cs_003",
    catalogId: "catalog_client_sector",
    catalogCode: "client_sector",
    item: "CS-003",
    name: "Químico",
    description: "Industria química",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "cs_004",
    catalogId: "catalog_client_sector",
    catalogCode: "client_sector",
    item: "CS-004",
    name: "Cosméticos",
    description: "Industria cosmética y personal care",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "cs_005",
    catalogId: "catalog_client_sector",
    catalogCode: "client_sector",
    item: "CS-005",
    name: "Agrícola",
    description: "Industria agrícola",
    status: "Activo",
    sortOrder: 5,
  },
  {
    id: "cs_006",
    catalogId: "catalog_client_sector",
    catalogCode: "client_sector",
    item: "CS-006",
    name: "Otros",
    description: "Otros sectores",
    status: "Activo",
    sortOrder: 6,
  },

  // ============ CLIENT_COUNTRY (País Cliente - 5 items) ============
  {
    id: "cc_001",
    catalogId: "catalog_client_country",
    catalogCode: "client_country",
    item: "PE",
    name: "Perú",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "cc_002",
    catalogId: "catalog_client_country",
    catalogCode: "client_country",
    item: "CL",
    name: "Chile",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "cc_003",
    catalogId: "catalog_client_country",
    catalogCode: "client_country",
    item: "CO",
    name: "Colombia",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "cc_004",
    catalogId: "catalog_client_country",
    catalogCode: "client_country",
    item: "EC",
    name: "Ecuador",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "cc_005",
    catalogId: "catalog_client_country",
    catalogCode: "client_country",
    item: "BR",
    name: "Brasil",
    status: "Activo",
    sortOrder: 5,
  },

  // ============ USER_ROLE (Rol de Usuario - 4 items) ============
  {
    id: "ur_001",
    catalogId: "catalog_user_role",
    catalogCode: "user_role",
    item: "UR-001",
    name: "Administrador",
    description: "Administrador del sistema",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "ur_002",
    catalogId: "catalog_user_role",
    catalogCode: "user_role",
    item: "UR-002",
    name: "Comercial",
    description: "Usuario comercial",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "ur_003",
    catalogId: "catalog_user_role",
    catalogCode: "user_role",
    item: "UR-003",
    name: "Master Data",
    description: "Gestor de datos maestros",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "ur_004",
    catalogId: "catalog_user_role",
    catalogCode: "user_role",
    item: "UR-004",
    name: "Customer Service",
    description: "Servicio al cliente",
    status: "Activo",
    sortOrder: 4,
  },

  // ============ USER_AREA (Área de Usuario - 5 items) ============
  {
    id: "ua_001",
    catalogId: "catalog_user_area",
    catalogCode: "user_area",
    item: "UA-001",
    name: "TI",
    description: "Tecnología e Información",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "ua_002",
    catalogId: "catalog_user_area",
    catalogCode: "user_area",
    item: "UA-002",
    name: "Comercial",
    description: "Área comercial",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "ua_003",
    catalogId: "catalog_user_area",
    catalogCode: "user_area",
    item: "UA-003",
    name: "Master Data",
    description: "Gestión de datos maestros",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "ua_004",
    catalogId: "catalog_user_area",
    catalogCode: "user_area",
    item: "UA-004",
    name: "Customer Service",
    description: "Servicio al cliente",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "ua_005",
    catalogId: "catalog_user_area",
    catalogCode: "user_area",
    item: "UA-005",
    name: "Operaciones",
    description: "Operaciones",
    status: "Activo",
    sortOrder: 5,
  },

  // ============ USER_STATUS (Estado de Usuario - 4 items) ============
  {
    id: "us_001",
    catalogId: "catalog_user_status",
    catalogCode: "user_status",
    item: "US-001",
    name: "Activo",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "us_002",
    catalogId: "catalog_user_status",
    catalogCode: "user_status",
    item: "US-002",
    name: "Inactivo",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "us_003",
    catalogId: "catalog_user_status",
    catalogCode: "user_status",
    item: "US-003",
    name: "Pendiente de Activación",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "us_004",
    catalogId: "catalog_user_status",
    catalogCode: "user_status",
    item: "US-004",
    name: "Bloqueado",
    status: "Activo",
    sortOrder: 4,
  },

  // ============ PORTFOLIO_STATUS (Estado de Portafolio - 2 items) ============
  {
    id: "ps_001",
    catalogId: "catalog_portfolio_status",
    catalogCode: "portfolio_status",
    item: "PS-001",
    name: "Activo",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "ps_002",
    catalogId: "catalog_portfolio_status",
    catalogCode: "portfolio_status",
    item: "PS-002",
    name: "Inactivo",
    status: "Activo",
    sortOrder: 2,
  },

  // ============ PRODUCT_STATUS (Estado de Producto - 2 items) ============
  {
    id: "pst_001",
    catalogId: "catalog_product_status",
    catalogCode: "product_status",
    item: "PST-001",
    name: "Activo",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "pst_002",
    catalogId: "catalog_product_status",
    catalogCode: "product_status",
    item: "PST-002",
    name: "Inactivo",
    status: "Activo",
    sortOrder: 2,
  },

  // ============ REQUEST_ORIGIN_PLANT (Planta de Origen de solicitud - 4 items) ============
  {
    id: "rop_001",
    catalogId: "catalog_request_origin_plant",
    catalogCode: "request_origin_plant",
    item: "AF-LIM",
    name: "AF Lima",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "rop_002",
    catalogId: "catalog_request_origin_plant",
    catalogCode: "request_origin_plant",
    item: "AF-CAL",
    name: "AF Cali",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "rop_003",
    catalogId: "catalog_request_origin_plant",
    catalogCode: "request_origin_plant",
    item: "AF-STN",
    name: "AF Santiago Norte",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "rop_004",
    catalogId: "catalog_request_origin_plant",
    catalogCode: "request_origin_plant",
    item: "AF-SL",
    name: "AF San Luis",
    status: "Activo",
    sortOrder: 4,
  },

  // ============ PRODUCT_LINE (Línea de Producto - 5 items) ============
  {
    id: "pl_001",
    catalogId: "catalog_product_line",
    catalogCode: "product_line",
    item: "PL-001",
    name: "Flexible Packaging",
    description: "Soluciones de empaque flexible",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "pl_002",
    catalogId: "catalog_product_line",
    catalogCode: "product_line",
    item: "PL-002",
    name: "Rigid Plastics",
    description: "Plásticos rígidos",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "pl_003",
    catalogId: "catalog_product_line",
    catalogCode: "product_line",
    item: "PL-003",
    name: "Carton Board",
    description: "Cartón para empaque",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "pl_004",
    catalogId: "catalog_product_line",
    catalogCode: "product_line",
    item: "PL-004",
    name: "Protective Solutions",
    description: "Soluciones de protección",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "pl_005",
    catalogId: "catalog_product_line",
    catalogCode: "product_line",
    item: "PL-005",
    name: "Specialty Solutions",
    description: "Soluciones especializadas",
    status: "Activo",
    sortOrder: 5,
  },

  // ============ MARKET_SEGMENT (Segmento de Mercado - 4 items) ============
  {
    id: "ms_001",
    catalogId: "catalog_market_segment",
    catalogCode: "market_segment",
    item: "MS-001",
    name: "Premium",
    description: "Segmento premium",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "ms_002",
    catalogId: "catalog_market_segment",
    catalogCode: "market_segment",
    item: "MS-002",
    name: "Standard",
    description: "Segmento estándar",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "ms_003",
    catalogId: "catalog_market_segment",
    catalogCode: "market_segment",
    item: "MS-003",
    name: "Económico",
    description: "Segmento económico",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "ms_004",
    catalogId: "catalog_market_segment",
    catalogCode: "market_segment",
    item: "MS-004",
    name: "Industrial",
    description: "Segmento industrial",
    status: "Activo",
    sortOrder: 4,
  },

  // ============ PACKAGING_MACHINE (Máquinas de Empaque - 18 items) ============
  // Máquinas para POUCH (VFFS y HFFS con Pouch)
  {
    id: "pm_001",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-001",
    name: "HFFS - Pouch 4 sellos",
    description: "Máquina horizontal para pouches con 4 sellos",
    wrappingType: "pouch",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "pm_002",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-002",
    name: "HFFS - Stand up Pouch - Base cuadrada",
    description: "Máquina para stand up pouch con base cuadrada",
    wrappingType: "pouch",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "pm_003",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-003",
    name: "HFFS - Stand up Pouch - Sello en K",
    description: "Máquina para stand up pouch con sello en K",
    wrappingType: "pouch",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "pm_004",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-004",
    name: "HFFS - Stand up Pouch - Sello Doy Pack",
    description: "Máquina para stand up pouch con sello doy pack",
    wrappingType: "pouch",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "pm_005",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-005",
    name: "HFFS - Flow Pack",
    description: "Máquina horizontal para flow pack",
    wrappingType: "pouch",
    status: "Activo",
    sortOrder: 5,
  },

  // Máquinas para BOLSA (VFFS y HFFS sin Pouch, Wicket, Twist Wrap, Envolvedora)
  {
    id: "pm_006",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-006",
    name: "VFFS - 3 sellos Pillow Pack",
    description: "Máquina vertical para pillow pack con 3 sellos",
    wrappingType: "bolsa",
    status: "Activo",
    sortOrder: 6,
  },
  {
    id: "pm_007",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-007",
    name: "VFFS - 3 sellos con Fuelle Lateral",
    description: "Máquina vertical con 3 sellos y fuelle lateral",
    wrappingType: "bolsa",
    status: "Activo",
    sortOrder: 7,
  },
  {
    id: "pm_008",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-008",
    name: "VFFS - 4 sellos con Mordaza Recta",
    description: "Máquina vertical con 4 sellos y mordaza recta",
    wrappingType: "bolsa",
    status: "Activo",
    sortOrder: 8,
  },
  {
    id: "pm_009",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-009",
    name: "VFFS - 4 sellos con Mordaza Giratoria",
    description: "Máquina vertical con 4 sellos y mordaza giratoria",
    wrappingType: "bolsa",
    status: "Activo",
    sortOrder: 9,
  },
  {
    id: "pm_010",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-010",
    name: "HFFS - Sobre Plano 4 sellos",
    description: "Máquina horizontal para sobres planos con 4 sellos",
    wrappingType: "bolsa",
    status: "Activo",
    sortOrder: 10,
  },
  {
    id: "pm_011",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-011",
    name: "Wicket",
    description: "Máquina wicket para bolsas de papel o plástico",
    wrappingType: "bolsa",
    status: "Activo",
    sortOrder: 11,
  },
  {
    id: "pm_012",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-012",
    name: "Wicket con Agregados",
    description: "Máquina wicket con sistemas de agregados",
    wrappingType: "bolsa",
    status: "Activo",
    sortOrder: 12,
  },
  {
    id: "pm_013",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-013",
    name: "Twist Wrap",
    description: "Máquina para empaques tipo twist (caramelo)",
    wrappingType: "bolsa",
    status: "Activo",
    sortOrder: 13,
  },
  {
    id: "pm_014",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-014",
    name: "Envolvedora",
    description: "Máquina envolvedora horizontal automática",
    wrappingType: "bolsa",
    status: "Activo",
    sortOrder: 14,
  },

  // Máquinas para LÁMINA (Etiquetadora, Túnel de Termoenogimiento, Manual)
  {
    id: "pm_015",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-015",
    name: "Etiquetadora Automática - Roll Fed",
    description: "Máquina etiquetadora automática alimentación rollo",
    wrappingType: "lamina",
    status: "Activo",
    sortOrder: 15,
  },
  {
    id: "pm_016",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-016",
    name: "Túnel de Termoenogimiento - TC Cortina (2 Bobinas)",
    description: "Túnel de calor con cortina de aire (2 bobinas)",
    wrappingType: "lamina",
    status: "Activo",
    sortOrder: 16,
  },
  {
    id: "pm_017",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-017",
    name: "Túnel de Termoenogimiento - TC Flujo continuo",
    description: "Túnel de calor con flujo continuo de aire",
    wrappingType: "lamina",
    status: "Activo",
    sortOrder: 17,
  },
  {
    id: "pm_018",
    catalogId: "catalog_packaging_machine",
    catalogCode: "packaging_machine",
    item: "MDC-018",
    name: "Manual",
    description: "Empaque manual",
    wrappingType: "lamina",
    status: "Activo",
    sortOrder: 18,
  },

  // ============ CORE_MATERIAL (Material del Core - 3 items) ============
  {
    id: "core_001",
    catalogId: "catalog_core_material",
    catalogCode: "core_material",
    item: "CM-001",
    name: "Cartón",
    description: "Core de cartón",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "core_002",
    catalogId: "catalog_core_material",
    catalogCode: "core_material",
    item: "CM-002",
    name: "Plástico",
    description: "Core de plástico",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "core_003",
    catalogId: "catalog_core_material",
    catalogCode: "core_material",
    item: "CM-003",
    name: "Metal",
    description: "Core metálico",
    status: "Activo",
    sortOrder: 3,
  },

  // ============ ZIPPER_TYPE (Tipo de Zipper - 3 items) ============
  {
    id: "zipper_001",
    catalogId: "catalog_zipper_type",
    catalogCode: "zipper_type",
    item: "ZT-001",
    name: "Convencional",
    description: "Zipper convencional",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "zipper_002",
    catalogId: "catalog_zipper_type",
    catalogCode: "zipper_type",
    item: "ZT-002",
    name: "String Zipper",
    description: "String Zipper",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "zipper_003",
    catalogId: "catalog_zipper_type",
    catalogCode: "zipper_type",
    item: "ZT-003",
    name: "No aplica",
    description: "No aplica",
    status: "Activo",
    sortOrder: 3,
  },

  // ============ VALVE_TYPE (Tipo de Válvula - 3 items) ============
  {
    id: "valve_001",
    catalogId: "catalog_valve_type",
    catalogCode: "valve_type",
    item: "VT-001",
    name: "Degasificadora",
    description: "Válvula degasificadora",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "valve_002",
    catalogId: "catalog_valve_type",
    catalogCode: "valve_type",
    item: "VT-002",
    name: "Dosificadora",
    description: "Válvula dosificadora",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "valve_003",
    catalogId: "catalog_valve_type",
    catalogCode: "valve_type",
    item: "VT-003",
    name: "No aplica",
    description: "No aplica",
    status: "Activo",
    sortOrder: 3,
  },

  // ============ ROUNDED_CORNERS_TYPE (Tipo de Esquinas Redondeadas - 2 items) ============
  {
    id: "rounded_001",
    catalogId: "catalog_rounded_corners_type",
    catalogCode: "rounded_corners_type",
    item: "RC-001",
    name: "Redondeo esquinas del fondo",
    description: "Redondeo esquinas del fondo",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "rounded_002",
    catalogId: "catalog_rounded_corners_type",
    catalogCode: "rounded_corners_type",
    item: "RC-002",
    name: "Redondeo todas las esquinas",
    description: "Redondeo todas las esquinas",
    status: "Activo",
    sortOrder: 2,
  },

  // ============ HANDLE_TYPE (Tipo de Asa - 2 items) ============
  {
    id: "handle_001",
    catalogId: "catalog_handle_type",
    catalogCode: "handle_type",
    item: "HT-001",
    name: "SIN ASA",
    description: "Sin asa",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "handle_002",
    catalogId: "catalog_handle_type",
    catalogCode: "handle_type",
    item: "HT-002",
    name: "CON ASA",
    description: "Con asa",
    status: "Activo",
    sortOrder: 2,
  },

  // ============ HANDLE_COLOR (Color de Asa - 9 items) ============
  {
    id: "handlecolor_001",
    catalogId: "catalog_handle_color",
    catalogCode: "handle_color",
    item: "HC-001",
    name: "Blanco",
    description: "Color blanco",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "handlecolor_002",
    catalogId: "catalog_handle_color",
    catalogCode: "handle_color",
    item: "HC-002",
    name: "Negro",
    description: "Color negro",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "handlecolor_003",
    catalogId: "catalog_handle_color",
    catalogCode: "handle_color",
    item: "HC-003",
    name: "Amarillo",
    description: "Color amarillo",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "handlecolor_004",
    catalogId: "catalog_handle_color",
    catalogCode: "handle_color",
    item: "HC-004",
    name: "Gris",
    description: "Color gris",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "handlecolor_005",
    catalogId: "catalog_handle_color",
    catalogCode: "handle_color",
    item: "HC-005",
    name: "Rojo",
    description: "Color rojo",
    status: "Activo",
    sortOrder: 5,
  },
  {
    id: "handlecolor_006",
    catalogId: "catalog_handle_color",
    catalogCode: "handle_color",
    item: "HC-006",
    name: "Rosado",
    description: "Color rosado",
    status: "Activo",
    sortOrder: 6,
  },
  {
    id: "handlecolor_007",
    catalogId: "catalog_handle_color",
    catalogCode: "handle_color",
    item: "HC-007",
    name: "Verde",
    description: "Color verde",
    status: "Activo",
    sortOrder: 7,
  },
  {
    id: "handlecolor_008",
    catalogId: "catalog_handle_color",
    catalogCode: "handle_color",
    item: "HC-008",
    name: "Azul",
    description: "Color azul",
    status: "Activo",
    sortOrder: 8,
  },
  {
    id: "handlecolor_009",
    catalogId: "catalog_handle_color",
    catalogCode: "handle_color",
    item: "HC-009",
    name: "Sin color",
    description: "Sin color",
    status: "Activo",
    sortOrder: 9,
  },

  // ============ POUCH_PERFORATION_TYPE (Tipo de Perforación Pouch - 4 items) ============
  {
    id: "perforation_001",
    catalogId: "catalog_pouch_perforation_type",
    catalogCode: "pouch_perforation_type",
    item: "PP-001",
    name: "Circular D 4 mm",
    description: "Perforación circular diámetro 4 mm",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "perforation_002",
    catalogId: "catalog_pouch_perforation_type",
    catalogCode: "pouch_perforation_type",
    item: "PP-002",
    name: "Circular D 6 mm",
    description: "Perforación circular diámetro 6 mm",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "perforation_003",
    catalogId: "catalog_pouch_perforation_type",
    catalogCode: "pouch_perforation_type",
    item: "PP-003",
    name: "Circular D 8 mm",
    description: "Perforación circular diámetro 8 mm",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "perforation_004",
    catalogId: "catalog_pouch_perforation_type",
    catalogCode: "pouch_perforation_type",
    item: "PP-004",
    name: "Circular 10 mm",
    description: "Perforación circular diámetro 10 mm",
    status: "Activo",
    sortOrder: 4,
  },

  // ============ EYELET_PERFORATION_TYPE (Tipo de Perforación Ojal - 7 items) ============
  {
    id: "eyelet_001",
    catalogId: "catalog_eyelet_perforation_type",
    catalogCode: "eyelet_perforation_type",
    item: "EP-001",
    name: "Ojal 50x15 mm",
    description: "Perforación ojal 50x15 mm",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "eyelet_002",
    catalogId: "catalog_eyelet_perforation_type",
    catalogCode: "eyelet_perforation_type",
    item: "EP-002",
    name: "Ojal 70x20 mm",
    description: "Perforación ojal 70x20 mm",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "eyelet_003",
    catalogId: "catalog_eyelet_perforation_type",
    catalogCode: "eyelet_perforation_type",
    item: "EP-003",
    name: "Ojal 78x20 mm",
    description: "Perforación ojal 78x20 mm",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "eyelet_004",
    catalogId: "catalog_eyelet_perforation_type",
    catalogCode: "eyelet_perforation_type",
    item: "EP-004",
    name: "Circular 4 mm",
    description: "Perforación circular diámetro 4 mm",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "eyelet_005",
    catalogId: "catalog_eyelet_perforation_type",
    catalogCode: "eyelet_perforation_type",
    item: "EP-005",
    name: "Circular 6 mm",
    description: "Perforación circular diámetro 6 mm",
    status: "Activo",
    sortOrder: 5,
  },
  {
    id: "eyelet_006",
    catalogId: "catalog_eyelet_perforation_type",
    catalogCode: "eyelet_perforation_type",
    item: "EP-006",
    name: "Circular 8 mm",
    description: "Perforación circular diámetro 8 mm",
    status: "Activo",
    sortOrder: 6,
  },
  {
    id: "eyelet_007",
    catalogId: "catalog_eyelet_perforation_type",
    catalogCode: "eyelet_perforation_type",
    item: "EP-007",
    name: "Circular 10 mm",
    description: "Perforación circular diámetro 10 mm",
    status: "Activo",
    sortOrder: 7,
  },

  // ============ WICKET_PERFORATION_TYPE (Tipo de Perforación Wicket - 10 items) ============
  {
    id: "wicket_perf_001",
    catalogId: "catalog_wicket_perforation_type",
    catalogCode: "wicket_perforation_type",
    item: "WP-001",
    name: "TBW",
    description: "Perforación TBW",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "wicket_perf_002",
    catalogId: "catalog_wicket_perforation_type",
    catalogCode: "wicket_perforation_type",
    item: "WP-002",
    name: "Ojal 50x15 mm",
    description: "Perforación ojal 50x15 mm",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "wicket_perf_003",
    catalogId: "catalog_wicket_perforation_type",
    catalogCode: "wicket_perforation_type",
    item: "WP-003",
    name: "Ojal 70x20 mm",
    description: "Perforación ojal 70x20 mm",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "wicket_perf_004",
    catalogId: "catalog_wicket_perforation_type",
    catalogCode: "wicket_perforation_type",
    item: "WP-004",
    name: "Ojal 78x20 mm",
    description: "Perforación ojal 78x20 mm",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "wicket_perf_005",
    catalogId: "catalog_wicket_perforation_type",
    catalogCode: "wicket_perforation_type",
    item: "WP-005",
    name: "Europunch 32x10 mm",
    description: "Perforación europunch 32x10 mm",
    status: "Activo",
    sortOrder: 5,
  },
  {
    id: "wicket_perf_006",
    catalogId: "catalog_wicket_perforation_type",
    catalogCode: "wicket_perforation_type",
    item: "WP-006",
    name: "Europunch 38x10 mm",
    description: "Perforación europunch 38x10 mm",
    status: "Activo",
    sortOrder: 6,
  },
  {
    id: "wicket_perf_007",
    catalogId: "catalog_wicket_perforation_type",
    catalogCode: "wicket_perforation_type",
    item: "WP-007",
    name: "Circular 4 mm",
    description: "Perforación circular diámetro 4 mm",
    status: "Activo",
    sortOrder: 7,
  },
  {
    id: "wicket_perf_008",
    catalogId: "catalog_wicket_perforation_type",
    catalogCode: "wicket_perforation_type",
    item: "WP-008",
    name: "Circular 6 mm",
    description: "Perforación circular diámetro 6 mm",
    status: "Activo",
    sortOrder: 8,
  },
  {
    id: "wicket_perf_009",
    catalogId: "catalog_wicket_perforation_type",
    catalogCode: "wicket_perforation_type",
    item: "WP-009",
    name: "Circular 8 mm",
    description: "Perforación circular diámetro 8 mm",
    status: "Activo",
    sortOrder: 9,
  },
  {
    id: "wicket_perf_010",
    catalogId: "catalog_wicket_perforation_type",
    catalogCode: "wicket_perforation_type",
    item: "WP-010",
    name: "Circular 10 mm",
    description: "Perforación circular diámetro 10 mm",
    status: "Activo",
    sortOrder: 10,
  },

  // ============ PRECUT_TYPE (Tipo de Pre-Corte - 3 items) ============
  {
    id: "precut_001",
    catalogId: "catalog_precut_type",
    catalogCode: "precut_type",
    item: "PC-001",
    name: "Pre-corte mecánico abre fácil",
    description: "Pre-corte mecánico abre fácil",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "precut_002",
    catalogId: "catalog_precut_type",
    catalogCode: "precut_type",
    item: "PC-002",
    name: "Pre-corte mecánico abre fácil sectorizado",
    description: "Pre-corte mecánico abre fácil sectorizado",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "precut_003",
    catalogId: "catalog_precut_type",
    catalogCode: "precut_type",
    item: "PC-003",
    name: "No aplica",
    description: "No aplica",
    status: "Activo",
    sortOrder: 3,
  },

  // ============ BAG_PERFORATION_TYPE (Tipo de Perforación Bolsa - 3 items) ============
  {
    id: "bagperforation_001",
    catalogId: "catalog_bag_perforation_type",
    catalogCode: "bag_perforation_type",
    item: "BP-001",
    name: "Cruz 5 mm",
    description: "Perforación cruz 5 mm",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "bagperforation_002",
    catalogId: "catalog_bag_perforation_type",
    catalogCode: "bag_perforation_type",
    item: "BP-002",
    name: "Cruz 7 mm",
    description: "Perforación cruz 7 mm",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "bagperforation_003",
    catalogId: "catalog_bag_perforation_type",
    catalogCode: "bag_perforation_type",
    item: "BP-003",
    name: "Media Luna D 5mm",
    description: "Perforación media luna D 5mm",
    status: "Activo",
    sortOrder: 3,
  },

  // NOTA: Los datos completos de catálogos adicionales (LAYER_MATERIAL con 58 items,
  // BLUEPRINT_FORMAT con 20 items, etc.) se deben cargar desde
  // src/shared/data/projectCatalogStorage.ts en la fase de migración.
  // Este seed contiene los catálogos críticos principales para inicializar el sistema.
];
