// Registro central de todos los catálogos disponibles en el sistema
// Basado en catálogos reales encontrados en:
// - src/shared/data/projectCatalogStorage.ts (27 catálogos)
// - src/shared/data/mockDatabase.ts (6 catálogos)

import type { CatalogDefinition } from "./catalog.types";

export const CATALOG_REGISTRY: CatalogDefinition[] = [
  // FASE 1 - CATÁLOGOS CRÍTICOS
  {
    id: "catalog_wrapping_type",
    code: "wrapping_type",
    name: "Tipo de Envoltura",
    description: "Tabla espejo del Sistema Integral: Tipos de envoltura válidos (POUCH, BOLSA, LÁMINA). Solo consulta/sincronización.",
    ownerModule: "products",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },
  // FASE 1 - CATÁLOGOS COMERCIALES (eliminados: subclassification, unit_measure, destination_country)

  // FASE 1 - CATÁLOGOS DE IMPRESIÓN Y ESTRUCTURA
  {
    id: "catalog_print_class",
    code: "print_class",
    name: "Clase de Impresión",
    description: "Niveles de calidad de impresión",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_print_type",
    code: "print_type",
    name: "Tipo de Impresión",
    description: "Tecnología de impresión (Flexografía, Rotograbado, Digital, Sin Impresión)",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_structure_type",
    code: "structure_type",
    name: "Tipo de Estructura",
    description: "Número de capas en la estructura",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },

  // FASE 1 - CATÁLOGOS DE PORTFOLIO
  {
    id: "catalog_final_use",
    code: "final_use",
    name: "Uso Final",
    description: "Categoría de uso final del producto con taxonomía (sector, segmento, subsegmento)",
    ownerModule: "portfolio",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_plant",
    code: "plant",
    name: "Planta de Origen de solicitud",
    description: "Catálogo maestro: Plantas de origen Amcor Flex (AF Lima, AF Cali, AF Santiago Norte, AF San Luis)",
    ownerModule: "portfolio",
    ownerSystem: "ODISEO",
    status: "active",
  },

  // FASE 2 - CATÁLOGOS DE ESPECIFICACIONES TÉCNICAS
  {
    id: "catalog_zipper_type",
    code: "zipper_type",
    name: "Tipo de Zipper",
    description: "Tipos de cierre tipo zipper",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_valve_type",
    code: "valve_type",
    name: "Tipo de Válvula",
    description: "Tipos de válvula para pouches",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_rounded_corners_type",
    code: "rounded_corners_type",
    name: "Tipo de Esquinas Redondeadas",
    description: "Opciones de redondeado de esquinas",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_pouch_perforation_type",
    code: "pouch_perforation_type",
    name: "Tipo de Perforación Pouch",
    description: "Tipos de perforación para pouches",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_eyelet_perforation_type",
    code: "eyelet_perforation_type",
    name: "Tipo de Perforación Ojal",
    description: "Tipos de perforación ojal para pouches con sello central aleta",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_bag_perforation_type",
    code: "bag_perforation_type",
    name: "Tipo de Perforación Bolsa",
    description: "Tipos de perforación para bolsas",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_wicket_perforation_type",
    code: "wicket_perforation_type",
    name: "Tipo de Perforación Wicket",
    description: "Tipos de perforación para bolsas wicket",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_precut_type",
    code: "precut_type",
    name: "Tipo de Pre-Corte",
    description: "Estilos de pre-corte",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_core_material",
    code: "core_material",
    name: "Material del Core",
    description: "Materiales para núcleo de rollo",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_handle_type",
    code: "handle_type",
    name: "Tipo de Asa",
    description: "Tipos de asa para bolsas",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_handle_color",
    code: "handle_color",
    name: "Color de Asa",
    description: "Colores disponibles para asa",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_handle_shape",
    code: "handle_shape",
    name: "Forma de Asa",
    description: "Formas disponibles para asa",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_doy_pack_base",
    code: "doy_pack_base",
    name: "Base Doy Pack",
    description: "Tipos de base para Doy Pack",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_color_objective",
    code: "color_objective",
    name: "Objetivo de Color",
    description: "Objetivos de color para impresión",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_press_approver",
    code: "press_approver",
    name: "Aprobador de Prensa",
    description: "Responsables de aprobación de prensa",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_special_design_specs",
    code: "special_design_specs",
    name: "Especificaciones Diseño Especial",
    description: "Especificaciones especiales de diseño",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_perforation_location",
    code: "perforation_location",
    name: "Ubicación de Perforación",
    description: "Ubicación de perforaciones en productos",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_other_accessories",
    code: "other_accessories",
    name: "Otros Accesorios",
    description: "Otros accesorios disponibles",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_doypack_bellows_type",
    code: "doypack_bellows_type",
    name: "Tipo de Fuelle",
    description: "Tipos de fuelle para Doy Pack",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_microperforado_side",
    code: "microperforado_side",
    name: "Lado de Microperforado",
    description: "Lado de microperforado en POUCH",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_seal_width",
    code: "seal_width",
    name: "Ancho de Sello Aleta",
    description: "Ancho de sello aleta en milímetros",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_microperforado_type",
    code: "microperforado_type",
    name: "Tipo Microperforado",
    description: "Tipos de microperforado",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },

  // FASE 2 - CATÁLOGOS AUXILIARES (Se eliminó "Sí/No" porque es un booleano, no un catálogo)

  // FASE 3 - CATÁLOGOS DE CLIENTES
  {
    id: "catalog_client_type",
    code: "client_type",
    name: "Tipo de Cliente",
    description: "Clasificación de clientes por tipo",
    ownerModule: "clients",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_client_sector",
    code: "client_sector",
    name: "Sector Cliente",
    description: "Sectores comerciales de clientes",
    ownerModule: "clients",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_client_country",
    code: "client_country",
    name: "País Cliente",
    description: "Países donde operan los clientes",
    ownerModule: "clients",
    ownerSystem: "ODISEO",
    status: "active",
  },

  // FASE 3 - CATÁLOGOS DE USUARIOS
  {
    id: "catalog_user_role",
    code: "user_role",
    name: "Rol de Usuario",
    description: "Roles disponibles en el sistema ODISEO",
    ownerModule: "users",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_user_area",
    code: "user_area",
    name: "Área de Usuario",
    description: "Áreas departamentales de la organización",
    ownerModule: "users",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_user_status",
    code: "user_status",
    name: "Estado de Usuario",
    description: "Tabla espejo del Sistema Integral: Estados del ciclo de vida de usuarios. Solo consulta/sincronización.",
    ownerModule: "users",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },

  // FASE 3 - CATÁLOGOS DE PORTAFOLIO
  {
    id: "catalog_portfolio_status",
    code: "portfolio_status",
    name: "Estado de Portafolio",
    description: "Estados del portafolio: Activo, Inactivo",
    ownerModule: "portfolio",
    ownerSystem: "ODISEO",
    status: "active",
  },
  // FASE 4 - CATÁLOGOS DEL SISTEMA INTEGRAL (TABLAS ESPEJO)
  {
    id: "catalog_packaging_machine",
    code: "packaging_machine",
    name: "Tipo de Envasado (Máquina de cliente)",
    description: "Tabla espejo del Sistema Integral: Tipos de envasado y máquinas de cliente. Solo consulta/sincronización.",
    ownerModule: "products",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },

  {
    id: "catalog_product_line",
    code: "product_line",
    name: "Línea de Producto",
    description: "Líneas de negocio o producto",
    ownerModule: "portfolio",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_market_segment",
    code: "market_segment",
    name: "Segmento de Mercado",
    description: "Segmentación del mercado",
    ownerModule: "portfolio",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_product_status",
    code: "product_status",
    name: "Estado de Producto",
    description: "Estados del ciclo de vida de productos",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },

  // CATÁLOGOS FALTANTES - PRODUCTOS
  {
    id: "catalog_application_technical",
    code: "application_technical",
    name: "Aplicación Técnica",
    description: "Aplicaciones técnicas de productos",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_classification",
    code: "classification",
    name: "Clasificación",
    description: "Clasificación de productos (Nuevo/Modificado)",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_format_plan",
    code: "format_plan",
    name: "Formato de Plano",
    description: "Formatos de plano disponibles",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_print_form",
    code: "print_form",
    name: "Forma de Impresión",
    description: "Formas de aplicación de impresión",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_number_colors",
    code: "number_colors",
    name: "Número de Colores",
    description: "Cantidad de colores en impresión",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_color_target",
    code: "color_target",
    name: "Objetivo de Color",
    description: "Objetivos para control de color",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_approver",
    code: "approver",
    name: "Aprobador",
    description: "Roles que aprueban productos",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_sub_segment",
    code: "sub_segment",
    name: "Sub-Segmento",
    description: "Sub-segmentación de mercado",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_final_use_application",
    code: "final_use_application",
    name: "Tipo de Aplicación - Uso Final",
    description: "Tipos de aplicación por uso final",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_lamina_format",
    code: "lamina_format",
    name: "Tipo de Formato Lámina",
    description: "Tipos de formato para láminas",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_winding_direction",
    code: "winding_direction",
    name: "Sentido de Embobinado",
    description: "Direcciones de embobinado",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_photocell_location",
    code: "photocell_location",
    name: "Ubicación de Fotocélula",
    description: "Ubicaciones de fotocélula en lámina",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_presentation_type",
    code: "presentation_type",
    name: "Tipo de Presentación",
    description: "Tipos de presentación de bolsa",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_bag_seal_type",
    code: "bag_seal_type",
    name: "Tipo de Sello Bolsa",
    description: "Tipos de sello para bolsas - Tabla espejo desde Sistema Integral",
    ownerModule: "products",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },
  {
    id: "catalog_finish",
    code: "finish",
    name: "Acabado",
    description: "Acabados disponibles",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_bag_bellows_type",
    code: "bag_bellows_type",
    name: "Tipo de Fuelle Bolsa",
    description: "Tipos de fuelle para bolsas",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_wicket_diameter",
    code: "wicket_diameter",
    name: "Diámetro de Wicket",
    description: "Diámetros de wicket disponibles",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_control_wicket_diameter",
    code: "control_wicket_diameter",
    name: "Diámetro de Wicket de Control",
    description: "Diámetros de wicket de control",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_precut_wicket_location",
    code: "precut_wicket_location",
    name: "Ubicación del Precorte Wicket",
    description: "Ubicaciones de precorte en wicket",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_stitching_separation",
    code: "stitching_separation",
    name: "Separación de Púas",
    description: "Separaciones de púas disponibles",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_pouch_family",
    code: "pouch_family",
    name: "Familia de Pouch",
    description: "Familias de pouch disponibles",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_standup_type",
    code: "standup_type",
    name: "Tipo de Stand Up",
    description: "Tipos de stand up para pouch",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_perforation_mouth_distance",
    code: "perforation_mouth_distance",
    name: "Distancia Boca a Perforación",
    description: "Distancias de boca a perforación (ojales, europunch, circular, esquinas redondas)",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_perforation_type_general",
    code: "perforation_type_general",
    name: "Tipo de Perforación General",
    description: "Tipos de perforación (ojales, europunch, circular, esquinas redondas)",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_bellows_width",
    code: "bellows_width",
    name: "Ancho de Fuelle Cerrado",
    description: "Ancho de fuelle cerrado en milímetros",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_lamina_type",
    code: "lamina_type",
    name: "Tipo de Lámina",
    description: "Tipos de lámina (Genérica, Tissue, Food)",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_control_wicket_location",
    code: "control_wicket_location",
    name: "Ubicación Wicket de Control",
    description: "Ubicaciones de wicket de control (Superior, Inferior)",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_precut_wicket_length",
    code: "precut_wicket_length",
    name: "Precorte Wicket Largo",
    description: "Longitudes de precorte en wicket (3mm, 4mm, 5mm, 6mm, 7mm)",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_margin_distance",
    code: "margin_distance",
    name: "Distancia Margen al Precorte Wicket",
    description: "Distancias del margen al precorte (Al borde, 4mm)",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },

  // ============ NUEVOS CATÁLOGOS A CENTRALIZAR ============

  {
    id: "catalog_client",
    code: "client",
    name: "Cliente",
    description: "Clientes del sistema - Tabla espejo desde Sistema Integral",
    ownerModule: "portfolio",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },
  {
    id: "catalog_executive",
    code: "executive",
    name: "Ejecutivo Comercial",
    description: "Ejecutivos comerciales - Tabla espejo desde Sistema Integral",
    ownerModule: "portfolio",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },
  {
    id: "catalog_unit_measure",
    code: "unit_measure",
    name: "Unidad de Medida",
    description: "Unidades de medida para especificaciones",
    ownerModule: "products",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },
  {
    id: "catalog_modification_new",
    code: "modification_new",
    name: "Modificación - Producto Nuevo",
    description: "Tipos de modificación para productos nuevos",
    ownerModule: "products",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },
  {
    id: "catalog_modification_modified",
    code: "modification_modified",
    name: "Modificación - Producto Modificado",
    description: "Tipos de modificación para productos modificados",
    ownerModule: "products",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },
  {
    id: "catalog_seals_count",
    code: "seals_count",
    name: "Cantidad de Sellos",
    description: "Cantidad de sellos en el empaque",
    ownerModule: "products",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },
  {
    id: "catalog_central_seal_material",
    code: "central_seal_material",
    name: "Material del Sello Central",
    description: "Materiales para sello central",
    ownerModule: "products",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },
  {
    id: "catalog_seal_type_gusset",
    code: "seal_type_gusset",
    name: "Tipo de Sello en Fuelle",
    description: "Tipos de sello para fuelle",
    ownerModule: "products",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },
  {
    id: "catalog_micron_pe",
    code: "micron_pe",
    name: "Micraje (Polietileno) por Capa",
    description: "Números de micraje para polietileno",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_material_packaging",
    code: "material_packaging",
    name: "Embalaje de Material",
    description: "Opciones de embalaje de material para exportación",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_export_packaging",
    code: "export_packaging",
    name: "Embalaje de Productos de Exportación",
    description: "Opciones de embalaje para productos de exportación",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_splices",
    code: "splices",
    name: "Empalmes",
    description: "Número de empalmes",
    ownerModule: "products",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },
];

export function getCatalogDefinition(code: string): CatalogDefinition | undefined {
  return CATALOG_REGISTRY.find((cat) => cat.code === code);
}

export function getCatalogDefinitionById(id: string): CatalogDefinition | undefined {
  return CATALOG_REGISTRY.find((cat) => cat.id === id);
}

export function getActiveCatalogs(): CatalogDefinition[] {
  return CATALOG_REGISTRY.filter((cat) => cat.status === "active");
}

export function getCatalogsByModule(module: string): CatalogDefinition[] {
  return CATALOG_REGISTRY.filter((cat) => cat.ownerModule === module);
}
