// Registro central de todos los catálogos disponibles en el sistema
// Basado en catálogos reales encontrados en:
// - src/shared/data/projectCatalogStorage.ts (27 catálogos)
// - src/shared/data/mockDatabase.ts (6 catálogos)

import type { CatalogDefinition } from "./catalog.types";

export const CATALOG_REGISTRY: CatalogDefinition[] = [
  // FASE 1 - CATÁLOGOS CRÍTICOS
  {
    id: "catalog_wrapping_type",
    code: "wrapping_type",
    name: "Tipo de Envoltura",
    description: "Tabla espejo del Sistema Integral: Tipos de envoltura válidos (POUCH, BOLSA, LÁMINA). Solo consulta/sincronización.",
    ownerModule: "products",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },
  // FASE 1 - CATÁLOGOS COMERCIALES (eliminados: subclassification, unit_measure, destination_country)

  // FASE 1 - CATÁLOGOS DE IMPRESIÓN Y ESTRUCTURA
  {
    id: "catalog_print_class",
    code: "print_class",
    name: "Clase de Impresión",
    description: "Niveles de calidad de impresión",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_print_type",
    code: "print_type",
    name: "Tipo de Impresión",
    description: "Tecnología de impresión (Flexografía, Rotograbado, Digital, Sin Impresión)",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_structure_type",
    code: "structure_type",
    name: "Tipo de Estructura",
    description: "Número de capas en la estructura",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },

  // FASE 1 - CATÁLOGOS DE PORTFOLIO
  {
    id: "catalog_final_use",
    code: "final_use",
    name: "Uso Final",
    description: "Categoría de uso final del producto con taxonomía (sector, segmento, subsegmento)",
    ownerModule: "portfolio",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_plant",
    code: "plant",
    name: "Planta de Origen de solicitud",
    description: "Catálogo maestro: Plantas de origen Amcor Flex (AF Lima, AF Cali, AF Santiago Norte, AF San Luis)",
    ownerModule: "portfolio",
    ownerSystem: "ODISEO",
    status: "active",
  },

  // FASE 2 - CATÁLOGOS DE ESPECIFICACIONES TÉCNICAS
  {
    id: "catalog_zipper_type",
    code: "zipper_type",
    name: "Tipo de Zipper",
    description: "Tipos de cierre tipo zipper",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_valve_type",
    code: "valve_type",
    name: "Tipo de Válvula",
    description: "Tipos de válvula para pouches",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_rounded_corners_type",
    code: "rounded_corners_type",
    name: "Tipo de Esquinas Redondeadas",
    description: "Opciones de redondeado de esquinas",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_pouch_perforation_type",
    code: "pouch_perforation_type",
    name: "Tipo de Perforación Pouch",
    description: "Tipos de perforación para pouches",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_eyelet_perforation_type",
    code: "eyelet_perforation_type",
    name: "Tipo de Perforación Ojal",
    description: "Tipos de perforación ojal para pouches con sello central aleta",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_bag_perforation_type",
    code: "bag_perforation_type",
    name: "Tipo de Perforación Bolsa",
    description: "Tipos de perforación para bolsas",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_wicket_perforation_type",
    code: "wicket_perforation_type",
    name: "Tipo de Perforación Wicket",
    description: "Tipos de perforación para bolsas wicket",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_precut_type",
    code: "precut_type",
    name: "Tipo de Pre-Corte",
    description: "Estilos de pre-corte",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_core_material",
    code: "core_material",
    name: "Material del Core",
    description: "Materiales para núcleo de rollo",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_handle_type",
    code: "handle_type",
    name: "Tipo de Asa",
    description: "Tipos de asa para bolsas",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_handle_color",
    code: "handle_color",
    name: "Color de Asa",
    description: "Colores disponibles para asa",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },

  // FASE 2 - CATÁLOGOS AUXILIARES (Se eliminó "Sí/No" porque es un booleano, no un catálogo)

  // FASE 3 - CATÁLOGOS DE CLIENTES
  {
    id: "catalog_client_type",
    code: "client_type",
    name: "Tipo de Cliente",
    description: "Clasificación de clientes por tipo",
    ownerModule: "clients",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_client_sector",
    code: "client_sector",
    name: "Sector Cliente",
    description: "Sectores comerciales de clientes",
    ownerModule: "clients",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_client_country",
    code: "client_country",
    name: "País Cliente",
    description: "Países donde operan los clientes",
    ownerModule: "clients",
    ownerSystem: "ODISEO",
    status: "active",
  },

  // FASE 3 - CATÁLOGOS DE USUARIOS
  {
    id: "catalog_user_role",
    code: "user_role",
    name: "Rol de Usuario",
    description: "Roles disponibles en el sistema ODISEO",
    ownerModule: "users",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_user_area",
    code: "user_area",
    name: "Área de Usuario",
    description: "Áreas departamentales de la organización",
    ownerModule: "users",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_user_status",
    code: "user_status",
    name: "Estado de Usuario",
    description: "Tabla espejo del Sistema Integral: Estados del ciclo de vida de usuarios. Solo consulta/sincronización.",
    ownerModule: "users",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },

  // FASE 3 - CATÁLOGOS DE PORTAFOLIO
  {
    id: "catalog_portfolio_status",
    code: "portfolio_status",
    name: "Estado de Portafolio",
    description: "Estados del portafolio: Activo, Inactivo",
    ownerModule: "portfolio",
    ownerSystem: "ODISEO",
    status: "active",
  },
  // FASE 4 - CATÁLOGOS DEL SISTEMA INTEGRAL (TABLAS ESPEJO)
  {
    id: "catalog_packaging_machine",
    code: "packaging_machine",
    name: "Tipo de Envasado (Máquina de cliente)",
    description: "Tabla espejo del Sistema Integral: Tipos de envasado y máquinas de cliente. Solo consulta/sincronización.",
    ownerModule: "products",
    ownerSystem: "SISTEMA_INTEGRAL",
    status: "active",
  },

  {
    id: "catalog_product_line",
    code: "product_line",
    name: "Línea de Producto",
    description: "Líneas de negocio o producto",
    ownerModule: "portfolio",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_market_segment",
    code: "market_segment",
    name: "Segmento de Mercado",
    description: "Segmentación del mercado",
    ownerModule: "portfolio",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_product_status",
    code: "product_status",
    name: "Estado de Producto",
    description: "Estados del ciclo de vida de productos",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },

  // CATÁLOGOS FALTANTES - PRODUCTOS
  {
    id: "catalog_application_technical",
    code: "application_technical",
    name: "Aplicación Técnica",
    description: "Aplicaciones técnicas de productos",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_classification",
    code: "classification",
    name: "Clasificación",
    description: "Clasificación de productos (Nuevo/Modificado)",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_format_plan",
    code: "format_plan",
    name: "Formato de Plano",
    description: "Formatos de plano disponibles",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_special_design_specs",
    code: "special_design_specs",
    name: "Especificaciones de Diseño Especiales",
    description: "Especificaciones especiales de diseño",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_print_form",
    code: "print_form",
    name: "Forma de Impresión",
    description: "Formas de aplicación de impresión",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_number_colors",
    code: "number_colors",
    name: "Número de Colores",
    description: "Cantidad de colores en impresión",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_color_target",
    code: "color_target",
    name: "Objetivo de Color",
    description: "Objetivos para control de color",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_approver",
    code: "approver",
    name: "Aprobador",
    description: "Roles que aprueban productos",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_sub_segment",
    code: "sub_segment",
    name: "Sub-Segmento",
    description: "Sub-segmentación de mercado",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_final_use_application",
    code: "final_use_application",
    name: "Tipo de Aplicación - Uso Final",
    description: "Tipos de aplicación por uso final",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_lamina_format",
    code: "lamina_format",
    name: "Tipo de Formato Lámina",
    description: "Tipos de formato para láminas",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_winding_direction",
    code: "winding_direction",
    name: "Sentido de Embobinado",
    description: "Direcciones de embobinado",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_photocell_location",
    code: "photocell_location",
    name: "Ubicación de Fotocélula",
    description: "Ubicaciones de fotocélula en lámina",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_presentation_type",
    code: "presentation_type",
    name: "Tipo de Presentación",
    description: "Tipos de presentación de bolsa",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_bag_seal_type",
    code: "bag_seal_type",
    name: "Tipo de Sello Bolsa",
    description: "Tipos de sello para bolsas",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_finish",
    code: "finish",
    name: "Acabado",
    description: "Acabados disponibles",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_bag_bellows_type",
    code: "bag_bellows_type",
    name: "Tipo de Fuelle Bolsa",
    description: "Tipos de fuelle para bolsas",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_wicket_diameter",
    code: "wicket_diameter",
    name: "Diámetro de Wicket",
    description: "Diámetros de wicket disponibles",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_control_wicket_diameter",
    code: "control_wicket_diameter",
    name: "Diámetro de Wicket de Control",
    description: "Diámetros de wicket de control",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_control_wicket_location",
    code: "control_wicket_location",
    name: "Ubicación Wicket de Control",
    description: "Ubicaciones de wicket de control",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_precut_wicket_location",
    code: "precut_wicket_location",
    name: "Ubicación del Precorte Wicket",
    description: "Ubicaciones de precorte en wicket",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_margin_distance",
    code: "margin_distance",
    name: "Distancia Margen al Precorte Wicket",
    description: "Distancias del margen al precorte",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_stitching_separation",
    code: "stitching_separation",
    name: "Separación de Púas",
    description: "Separaciones de púas disponibles",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_pouch_family",
    code: "pouch_family",
    name: "Familia de Pouch",
    description: "Familias de pouch disponibles",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_standup_type",
    code: "standup_type",
    name: "Tipo de Stand Up",
    description: "Tipos de stand up para pouch",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
  {
    id: "catalog_doypack_base",
    code: "doypack_base",
    name: "Base del Doypack",
    description: "Formas de base para doypack",
    ownerModule: "products",
    ownerSystem: "ODISEO",
    status: "active",
  },
];

export function getCatalogDefinition(code: string): CatalogDefinition | undefined {
  return CATALOG_REGISTRY.find((cat) => cat.code === code);
}

export function getCatalogDefinitionById(id: string): CatalogDefinition | undefined {
  return CATALOG_REGISTRY.find((cat) => cat.id === id);
}

export function getActiveCatalogs(): CatalogDefinition[] {
  return CATALOG_REGISTRY.filter((cat) => cat.status === "active");
}

export function getCatalogsByModule(module: string): CatalogDefinition[] {
  return CATALOG_REGISTRY.filter((cat) => cat.ownerModule === module);
}
