// Datos reales de catálogos centralizados
// Fuente: src/shared/data/projectCatalogStorage.ts y mockDatabase.ts
// NO contiene datos ficticios, solo datos existentes validados en el sistema

import type { CatalogValue } from "./catalog.types";

export const CATALOG_VALUES_SEED: CatalogValue[] = [
  // ============ WRAPPING_TYPE (Envolturas - 3 items) ============
  {
    id: "wrap_001",
    catalogId: "catalog_wrapping_type",
    catalogCode: "wrapping_type",
    item: "ENV-001",
    name: "POUCH",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "wrap_002",
    catalogId: "catalog_wrapping_type",
    catalogCode: "wrapping_type",
    item: "ENV-002",
    name: "BOLSA",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "wrap_003",
    catalogId: "catalog_wrapping_type",
    catalogCode: "wrapping_type",
    item: "ENV-003",
    name: "LÁMINA",
    status: "Activo",
    sortOrder: 3,
  },

  // ============ CLASSIFICATION (Clasificación - 3 items) ============
  {
    id: "class_001",
    catalogId: "catalog_classification",
    catalogCode: "classification",
    item: "CLASS-001",
    name: "Nuevo",
    description: "Producto completamente nuevo",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "class_002",
    catalogId: "catalog_classification",
    catalogCode: "classification",
    item: "CLASS-002",
    name: "Modificado",
    description: "Producto con modificaciones",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "class_003",
    catalogId: "catalog_classification",
    catalogCode: "classification",
    item: "CLASS-003",
    name: "Estándar",
    description: "Producto estándar existente",
    status: "Activo",
    sortOrder: 3,
  },

  // ============ SUBCLASSIFICATION (Sub-clasificación - 5 items) ============
  {
    id: "subclass_001",
    catalogId: "catalog_subclassification",
    catalogCode: "subclassification",
    item: "SUBCLASS-001",
    name: "SFDC - R&D",
    description: "Solicitud de desarrollo cliente - R&D",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "subclass_002",
    catalogId: "catalog_subclassification",
    catalogCode: "subclassification",
    item: "SUBCLASS-002",
    name: "SFDC - Técnica",
    description: "Solicitud de desarrollo cliente - Técnica",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "subclass_003",
    catalogId: "catalog_subclassification",
    catalogCode: "subclassification",
    item: "SUBCLASS-003",
    name: "Estructura",
    description: "Cambio en estructura",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "subclass_004",
    catalogId: "catalog_subclassification",
    catalogCode: "subclassification",
    item: "SUBCLASS-004",
    name: "Extensiones en línea",
    description: "Extensiones de línea existente",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "subclass_005",
    catalogId: "catalog_subclassification",
    catalogCode: "subclassification",
    item: "SUBCLASS-005",
    name: "No aplica",
    description: "No aplica sub-clasificación",
    status: "Activo",
    sortOrder: 5,
  },

  // ============ UNIT_MEASURE (Unidad de Medida - 7 items) ============
  {
    id: "um_001",
    catalogId: "catalog_unit_measure",
    catalogCode: "unit_measure",
    item: "UM-001",
    name: "unidad",
    description: "Unidad",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "um_002",
    catalogId: "catalog_unit_measure",
    catalogCode: "unit_measure",
    item: "UM-002",
    name: "millares",
    description: "Millares (miles de unidades)",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "um_003",
    catalogId: "catalog_unit_measure",
    catalogCode: "unit_measure",
    item: "UM-003",
    name: "kilos",
    description: "Kilogramos",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "um_004",
    catalogId: "catalog_unit_measure",
    catalogCode: "unit_measure",
    item: "UM-004",
    name: "metros",
    description: "Metros lineales",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "um_005",
    catalogId: "catalog_unit_measure",
    catalogCode: "unit_measure",
    item: "UM-005",
    name: "millones_unidades",
    description: "Millones de unidades",
    status: "Activo",
    sortOrder: 5,
  },
  {
    id: "um_006",
    catalogId: "catalog_unit_measure",
    catalogCode: "unit_measure",
    item: "UM-006",
    name: "toneladas",
    description: "Toneladas",
    status: "Activo",
    sortOrder: 6,
  },
  {
    id: "um_007",
    catalogId: "catalog_unit_measure",
    catalogCode: "unit_measure",
    item: "UM-007",
    name: "rollos",
    description: "Rollos",
    status: "Activo",
    sortOrder: 7,
  },

  // ============ SALE_TYPE (Tipo de Venta - 2 items) ============
  {
    id: "st_001",
    catalogId: "catalog_sale_type",
    catalogCode: "sale_type",
    item: "ST-001",
    name: "Nacional",
    description: "Venta dentro del país",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "st_002",
    catalogId: "catalog_sale_type",
    catalogCode: "sale_type",
    item: "ST-002",
    name: "Internacional",
    description: "Exportación",
    status: "Activo",
    sortOrder: 2,
  },

  // ============ INCOTERM (Incoterms - 11 items) ============
  {
    id: "ic_001",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-001",
    name: "EXW",
    description: "Ex Works - En fábrica",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "ic_002",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-002",
    name: "FCA",
    description: "Free Carrier - Libre transportista",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "ic_003",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-003",
    name: "CPT",
    description: "Carriage Paid To - Transporte pagado hasta",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "ic_004",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-004",
    name: "CIP",
    description: "Carriage and Insurance Paid - Transporte y seguro pagado",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "ic_005",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-005",
    name: "DAP",
    description: "Delivered at Place - Entregado en lugar",
    status: "Activo",
    sortOrder: 5,
  },
  {
    id: "ic_006",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-006",
    name: "DPU",
    description: "Delivered at Place Unloaded - Entregado descargado",
    status: "Activo",
    sortOrder: 6,
  },
  {
    id: "ic_007",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-007",
    name: "DDP",
    description: "Delivered Duty Paid - Entregado derechos pagados",
    status: "Activo",
    sortOrder: 7,
  },
  {
    id: "ic_008",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-008",
    name: "FAS",
    description: "Free Alongside Ship - Libre al costado del buque",
    status: "Activo",
    sortOrder: 8,
  },
  {
    id: "ic_009",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-009",
    name: "FOB",
    description: "Free On Board - Libre a bordo",
    status: "Activo",
    sortOrder: 9,
  },
  {
    id: "ic_010",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-010",
    name: "CFR",
    description: "Cost and Freight - Costo y flete",
    status: "Activo",
    sortOrder: 10,
  },
  {
    id: "ic_011",
    catalogId: "catalog_incoterm",
    catalogCode: "incoterm",
    item: "IC-011",
    name: "CIF",
    description: "Cost, Insurance and Freight - Costo, seguro y flete",
    status: "Activo",
    sortOrder: 11,
  },

  // ============ DESTINATION_COUNTRY (Países de Destino - 20 items) ============
  {
    id: "dc_001",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "PE",
    name: "Perú",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "dc_002",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "CL",
    name: "Chile",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "dc_003",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "CO",
    name: "Colombia",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "dc_004",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "EC",
    name: "Ecuador",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "dc_005",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "AR",
    name: "Argentina",
    status: "Activo",
    sortOrder: 5,
  },
  {
    id: "dc_006",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "BR",
    name: "Brasil",
    status: "Activo",
    sortOrder: 6,
  },
  {
    id: "dc_007",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "BO",
    name: "Bolivia",
    status: "Activo",
    sortOrder: 7,
  },
  {
    id: "dc_008",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "UY",
    name: "Uruguay",
    status: "Activo",
    sortOrder: 8,
  },
  {
    id: "dc_009",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "PY",
    name: "Paraguay",
    status: "Activo",
    sortOrder: 9,
  },
  {
    id: "dc_010",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "VE",
    name: "Venezuela",
    status: "Activo",
    sortOrder: 10,
  },
  {
    id: "dc_011",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "MX",
    name: "México",
    status: "Activo",
    sortOrder: 11,
  },
  {
    id: "dc_012",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "US",
    name: "Estados Unidos",
    status: "Activo",
    sortOrder: 12,
  },
  {
    id: "dc_013",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "CA",
    name: "Canadá",
    status: "Activo",
    sortOrder: 13,
  },
  {
    id: "dc_014",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "PA",
    name: "Panamá",
    status: "Activo",
    sortOrder: 14,
  },
  {
    id: "dc_015",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "CR",
    name: "Costa Rica",
    status: "Activo",
    sortOrder: 15,
  },
  {
    id: "dc_016",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "GT",
    name: "Guatemala",
    status: "Activo",
    sortOrder: 16,
  },
  {
    id: "dc_017",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "SV",
    name: "El Salvador",
    status: "Activo",
    sortOrder: 17,
  },
  {
    id: "dc_018",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "HN",
    name: "Honduras",
    status: "Activo",
    sortOrder: 18,
  },
  {
    id: "dc_019",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "NI",
    name: "Nicaragua",
    status: "Activo",
    sortOrder: 19,
  },
  {
    id: "dc_020",
    catalogId: "catalog_destination_country",
    catalogCode: "destination_country",
    item: "DO",
    name: "República Dominicana",
    status: "Activo",
    sortOrder: 20,
  },

  // ============ CURRENCY (Moneda - 3 items) ============
  {
    id: "cur_001",
    catalogId: "catalog_currency",
    catalogCode: "currency",
    item: "PEN",
    name: "Soles",
    description: "Sol peruano",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "cur_002",
    catalogId: "catalog_currency",
    catalogCode: "currency",
    item: "USD",
    name: "Dólares",
    description: "Dólar estadounidense",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "cur_003",
    catalogId: "catalog_currency",
    catalogCode: "currency",
    item: "EUR",
    name: "Euros",
    description: "Euro",
    status: "Activo",
    sortOrder: 3,
  },

  // ============ PRINT_CLASS (Clase de Impresión - 6 items) ============
  {
    id: "pc_001",
    catalogId: "catalog_print_class",
    catalogCode: "print_class",
    item: "PC-001",
    name: "Sencilla",
    description: "Impresión sencilla",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "pc_002",
    catalogId: "catalog_print_class",
    catalogCode: "print_class",
    item: "PC-002",
    name: "Alta Definición",
    description: "HD - Alta definición",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "pc_003",
    catalogId: "catalog_print_class",
    catalogCode: "print_class",
    item: "PC-003",
    name: "Ultra HD",
    description: "UHD - Ultra alta definición",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "pc_004",
    catalogId: "catalog_print_class",
    catalogCode: "print_class",
    item: "PC-004",
    name: "ESG (Extended Gamut)",
    description: "Gama extendida de colores",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "pc_005",
    catalogId: "catalog_print_class",
    catalogCode: "print_class",
    item: "PC-005",
    name: "Omnia",
    description: "Tecnología Omnia Amcor",
    status: "Activo",
    sortOrder: 5,
  },
  {
    id: "pc_006",
    catalogId: "catalog_print_class",
    catalogCode: "print_class",
    item: "PC-006",
    name: "Sin Impresión",
    description: "Película sin impresión",
    status: "Activo",
    sortOrder: 6,
  },

  // ============ PRINT_TYPE (Tipo de Impresión - 4 items) ============
  {
    id: "pt_001",
    catalogId: "catalog_print_type",
    catalogCode: "print_type",
    item: "PT-001",
    name: "Flexografía",
    description: "Impresión flexográfica",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "pt_002",
    catalogId: "catalog_print_type",
    catalogCode: "print_type",
    item: "PT-002",
    name: "Rotograbado",
    description: "Impresión en rotograbado",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "pt_003",
    catalogId: "catalog_print_type",
    catalogCode: "print_type",
    item: "PT-003",
    name: "Digital",
    description: "Impresión digital",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "pt_004",
    catalogId: "catalog_print_type",
    catalogCode: "print_type",
    item: "PT-004",
    name: "Sin Impresión",
    description: "Sin impresión",
    status: "Activo",
    sortOrder: 4,
  },

  // ============ STRUCTURE_TYPE (Tipo de Estructura - 6 items) ============
  {
    id: "st_str_001",
    catalogId: "catalog_structure_type",
    catalogCode: "structure_type",
    item: "ST-001",
    name: "Monocapa",
    description: "Estructura de una capa",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "st_str_002",
    catalogId: "catalog_structure_type",
    catalogCode: "structure_type",
    item: "ST-002",
    name: "Dúplex",
    description: "Estructura de dos capas",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "st_str_003",
    catalogId: "catalog_structure_type",
    catalogCode: "structure_type",
    item: "ST-003",
    name: "Tríplex",
    description: "Estructura de tres capas",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "st_str_004",
    catalogId: "catalog_structure_type",
    catalogCode: "structure_type",
    item: "ST-004",
    name: "Cuádruple",
    description: "Estructura de cuatro capas",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "st_str_005",
    catalogId: "catalog_structure_type",
    catalogCode: "structure_type",
    item: "ST-005",
    name: "Coextruida",
    description: "Estructura coextruida",
    status: "Activo",
    sortOrder: 5,
  },
  {
    id: "st_str_006",
    catalogId: "catalog_structure_type",
    catalogCode: "structure_type",
    item: "ST-006",
    name: "Laminada",
    description: "Estructura laminada",
    status: "Activo",
    sortOrder: 6,
  },

  // ============ FINAL_USE (Uso Final - 10+ items de FINAL_USE_CATALOG) ============
  {
    id: "fu_001",
    catalogId: "catalog_final_use",
    catalogCode: "final_use",
    item: "UF-001",
    name: "Adhesive Bandages/Plasters",
    description: "Categoría Healthcare",
    status: "Activo",
    sortOrder: 1,
  },

  // ============ PLANT (Plantas - 4 items) ============
  {
    id: "plant_001",
    catalogId: "catalog_plant",
    catalogCode: "plant",
    item: "AF-LIM",
    name: "AF Lima",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "plant_002",
    catalogId: "catalog_plant",
    catalogCode: "plant",
    item: "AF-SL",
    name: "AF San Luis",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "plant_003",
    catalogId: "catalog_plant",
    catalogCode: "plant",
    item: "AF-CAL",
    name: "AF Cali",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "plant_004",
    catalogId: "catalog_plant",
    catalogCode: "plant",
    item: "AF-STN",
    name: "AF Santiago Norte",
    status: "Activo",
    sortOrder: 4,
  },

  // ============ STATUS (Estados - 4 items) ============
  {
    id: "status_001",
    catalogId: "catalog_status",
    catalogCode: "status",
    item: "REG",
    name: "Registrado",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "status_002",
    catalogId: "catalog_status",
    catalogCode: "status",
    item: "REV",
    name: "En revisión",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "status_003",
    catalogId: "catalog_status",
    catalogCode: "status",
    item: "CER",
    name: "Cerrado",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "status_004",
    catalogId: "catalog_status",
    catalogCode: "status",
    item: "DES",
    name: "Desestimado",
    status: "Activo",
    sortOrder: 4,
  },

  // ============ YES_NO (Sí/No - 2 items) ============
  {
    id: "yn_001",
    catalogId: "catalog_yes_no",
    catalogCode: "yes_no",
    item: "YN-001",
    name: "Sí",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "yn_002",
    catalogId: "catalog_yes_no",
    catalogCode: "yes_no",
    item: "YN-002",
    name: "No",
    status: "Activo",
    sortOrder: 2,
  },

  // ============ CLIENT_TYPE (Tipo de Cliente - 4 items) ============
  {
    id: "ct_001",
    catalogId: "catalog_client_type",
    catalogCode: "client_type",
    item: "CT-001",
    name: "Distribuidor",
    description: "Cliente distribuidor",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "ct_002",
    catalogId: "catalog_client_type",
    catalogCode: "client_type",
    item: "CT-002",
    name: "Fabricante",
    description: "Cliente fabricante",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "ct_003",
    catalogId: "catalog_client_type",
    catalogCode: "client_type",
    item: "CT-003",
    name: "Retailer",
    description: "Cliente retail/comercio",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "ct_004",
    catalogId: "catalog_client_type",
    catalogCode: "client_type",
    item: "CT-004",
    name: "Consumidor Final",
    description: "Consumidor directo",
    status: "Activo",
    sortOrder: 4,
  },

  // ============ CLIENT_SECTOR (Sector Cliente - 6 items) ============
  {
    id: "cs_001",
    catalogId: "catalog_client_sector",
    catalogCode: "client_sector",
    item: "CS-001",
    name: "Alimentos y Bebidas",
    description: "Industria de alimentos y bebidas",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "cs_002",
    catalogId: "catalog_client_sector",
    catalogCode: "client_sector",
    item: "CS-002",
    name: "Farmacéutico",
    description: "Industria farmacéutica",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "cs_003",
    catalogId: "catalog_client_sector",
    catalogCode: "client_sector",
    item: "CS-003",
    name: "Químico",
    description: "Industria química",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "cs_004",
    catalogId: "catalog_client_sector",
    catalogCode: "client_sector",
    item: "CS-004",
    name: "Cosméticos",
    description: "Industria cosmética y personal care",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "cs_005",
    catalogId: "catalog_client_sector",
    catalogCode: "client_sector",
    item: "CS-005",
    name: "Agrícola",
    description: "Industria agrícola",
    status: "Activo",
    sortOrder: 5,
  },
  {
    id: "cs_006",
    catalogId: "catalog_client_sector",
    catalogCode: "client_sector",
    item: "CS-006",
    name: "Otros",
    description: "Otros sectores",
    status: "Activo",
    sortOrder: 6,
  },

  // ============ CLIENT_COUNTRY (País Cliente - 5 items) ============
  {
    id: "cc_001",
    catalogId: "catalog_client_country",
    catalogCode: "client_country",
    item: "PE",
    name: "Perú",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "cc_002",
    catalogId: "catalog_client_country",
    catalogCode: "client_country",
    item: "CL",
    name: "Chile",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "cc_003",
    catalogId: "catalog_client_country",
    catalogCode: "client_country",
    item: "CO",
    name: "Colombia",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "cc_004",
    catalogId: "catalog_client_country",
    catalogCode: "client_country",
    item: "EC",
    name: "Ecuador",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "cc_005",
    catalogId: "catalog_client_country",
    catalogCode: "client_country",
    item: "BR",
    name: "Brasil",
    status: "Activo",
    sortOrder: 5,
  },

  // ============ USER_ROLE (Rol de Usuario - 4 items) ============
  {
    id: "ur_001",
    catalogId: "catalog_user_role",
    catalogCode: "user_role",
    item: "UR-001",
    name: "Administrador",
    description: "Administrador del sistema",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "ur_002",
    catalogId: "catalog_user_role",
    catalogCode: "user_role",
    item: "UR-002",
    name: "Comercial",
    description: "Usuario comercial",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "ur_003",
    catalogId: "catalog_user_role",
    catalogCode: "user_role",
    item: "UR-003",
    name: "Master Data",
    description: "Gestor de datos maestros",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "ur_004",
    catalogId: "catalog_user_role",
    catalogCode: "user_role",
    item: "UR-004",
    name: "Customer Service",
    description: "Servicio al cliente",
    status: "Activo",
    sortOrder: 4,
  },

  // ============ USER_AREA (Área de Usuario - 5 items) ============
  {
    id: "ua_001",
    catalogId: "catalog_user_area",
    catalogCode: "user_area",
    item: "UA-001",
    name: "TI",
    description: "Tecnología e Información",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "ua_002",
    catalogId: "catalog_user_area",
    catalogCode: "user_area",
    item: "UA-002",
    name: "Comercial",
    description: "Área comercial",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "ua_003",
    catalogId: "catalog_user_area",
    catalogCode: "user_area",
    item: "UA-003",
    name: "Master Data",
    description: "Gestión de datos maestros",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "ua_004",
    catalogId: "catalog_user_area",
    catalogCode: "user_area",
    item: "UA-004",
    name: "Customer Service",
    description: "Servicio al cliente",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "ua_005",
    catalogId: "catalog_user_area",
    catalogCode: "user_area",
    item: "UA-005",
    name: "Operaciones",
    description: "Operaciones",
    status: "Activo",
    sortOrder: 5,
  },

  // ============ USER_STATUS (Estado de Usuario - 4 items) ============
  {
    id: "us_001",
    catalogId: "catalog_user_status",
    catalogCode: "user_status",
    item: "US-001",
    name: "Activo",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "us_002",
    catalogId: "catalog_user_status",
    catalogCode: "user_status",
    item: "US-002",
    name: "Inactivo",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "us_003",
    catalogId: "catalog_user_status",
    catalogCode: "user_status",
    item: "US-003",
    name: "Pendiente de Activación",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "us_004",
    catalogId: "catalog_user_status",
    catalogCode: "user_status",
    item: "US-004",
    name: "Bloqueado",
    status: "Activo",
    sortOrder: 4,
  },

  // ============ PORTFOLIO_STATUS (Estado de Portafolio - 4 items) ============
  {
    id: "ps_001",
    catalogId: "catalog_portfolio_status",
    catalogCode: "portfolio_status",
    item: "PS-001",
    name: "Activo",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "ps_002",
    catalogId: "catalog_portfolio_status",
    catalogCode: "portfolio_status",
    item: "PS-002",
    name: "Inactivo",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "ps_003",
    catalogId: "catalog_portfolio_status",
    catalogCode: "portfolio_status",
    item: "PS-003",
    name: "En Desarrollo",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "ps_004",
    catalogId: "catalog_portfolio_status",
    catalogCode: "portfolio_status",
    item: "PS-004",
    name: "Aprobado",
    status: "Activo",
    sortOrder: 4,
  },

  // ============ PRODUCT_LINE (Línea de Producto - 5 items) ============
  {
    id: "pl_001",
    catalogId: "catalog_product_line",
    catalogCode: "product_line",
    item: "PL-001",
    name: "Flexible Packaging",
    description: "Soluciones de empaque flexible",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "pl_002",
    catalogId: "catalog_product_line",
    catalogCode: "product_line",
    item: "PL-002",
    name: "Rigid Plastics",
    description: "Plásticos rígidos",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "pl_003",
    catalogId: "catalog_product_line",
    catalogCode: "product_line",
    item: "PL-003",
    name: "Carton Board",
    description: "Cartón para empaque",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "pl_004",
    catalogId: "catalog_product_line",
    catalogCode: "product_line",
    item: "PL-004",
    name: "Protective Solutions",
    description: "Soluciones de protección",
    status: "Activo",
    sortOrder: 4,
  },
  {
    id: "pl_005",
    catalogId: "catalog_product_line",
    catalogCode: "product_line",
    item: "PL-005",
    name: "Specialty Solutions",
    description: "Soluciones especializadas",
    status: "Activo",
    sortOrder: 5,
  },

  // ============ MARKET_SEGMENT (Segmento de Mercado - 4 items) ============
  {
    id: "ms_001",
    catalogId: "catalog_market_segment",
    catalogCode: "market_segment",
    item: "MS-001",
    name: "Premium",
    description: "Segmento premium",
    status: "Activo",
    sortOrder: 1,
  },
  {
    id: "ms_002",
    catalogId: "catalog_market_segment",
    catalogCode: "market_segment",
    item: "MS-002",
    name: "Standard",
    description: "Segmento estándar",
    status: "Activo",
    sortOrder: 2,
  },
  {
    id: "ms_003",
    catalogId: "catalog_market_segment",
    catalogCode: "market_segment",
    item: "MS-003",
    name: "Económico",
    description: "Segmento económico",
    status: "Activo",
    sortOrder: 3,
  },
  {
    id: "ms_004",
    catalogId: "catalog_market_segment",
    catalogCode: "market_segment",
    item: "MS-004",
    name: "Industrial",
    description: "Segmento industrial",
    status: "Activo",
    sortOrder: 4,
  },

  // NOTA: Los datos completos de catálogos adicionales (LAYER_MATERIAL con 58 items,
  // BLUEPRINT_FORMAT con 20 items, etc.) se deben cargar desde
  // src/shared/data/projectCatalogStorage.ts en la fase de migración.
  // Este seed contiene los catálogos críticos principales para inicializar el sistema.
];
